# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6241fe55b74feb6574b2ba41692e194c5b3123c66432c04af760c0defe7a28fa037019a9d4bae61d0ec8dbc643a782b77f2c16f5cee31665f967b7fb93eb9623

test:
  secret_key_base: abd8357c2ebf00a435751716583c01c4cd0e7f0b572a7acb0eb4f3638466d29ef777588c039cbbc62a2ec2c4662a5f6f98e004df06af788f335806f8fbbd84f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
